USE Airline_Analysis;

CREATE TABLE flights (
YEAR SMALLINT,
MONTH TINYINT,
DAY TINYINT,
DAY_OF_WEEK TINYINT,
AIRLINE VARCHAR(5),
FLIGHT_NUMBER INT,
TAIL_NUMBER VARCHAR(10) NULL,
ORIGIN_AIRPORT VARCHAR(5),
DESTINATION_AIRPORT VARCHAR(5),

SCHEDULED_DEPARTURE INT,
DEPARTURE_TIME INT NULL,
DEPARTURE_DELAY SMALLINT NULL,

TAXI_OUT SMALLINT NULL,
WHEELS_OFF INT NULL,
SCHEDULED_TIME SMALLINT NULL,
ELAPSED_TIME SMALLINT NULL,
AIR_TIME SMALLINT NULL,

DISTANCE INT,

WHEELS_ON INT NULL,
TAXI_IN SMALLINT NULL,

SCHEDULED_ARRIVAL INT,
ARRIVAL_TIME INT NULL,
ARRIVAL_DELAY SMALLINT NULL,

DIVERTED BIT,
CANCELLED BIT,
CANCELLATION_REASON VARCHAR(5) NULL,

AIR_SYSTEM_DELAY SMALLINT NULL,
SECURITY_DELAY SMALLINT NULL,
AIRLINE_DELAY SMALLINT NULL,
LATE_AIRCRAFT_DELAY SMALLINT NULL,
WEATHER_DELAY SMALLINT NULL
);

BULK INSERT flights
FROM 'C:\Users\hp\OneDrive\Desktop\Data Analytics Project\Emirates Analysis\flights.csv'
WITH (
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0a',
TABLOCK
);

SELECT COUNT(*) FROM flights;
Select * from flights

SELECT TOP 10 *
FROM flights;

--- Checking and lisitng colum which have null vlaues from flights dataset
SELECT column_name, null_count
FROM (
    SELECT 'TAIL_NUMBER' AS column_name, COUNT(*) - COUNT(TAIL_NUMBER) AS null_count FROM flights
    UNION ALL
    SELECT 'DEPARTURE_TIME', COUNT(*) - COUNT(DEPARTURE_TIME) FROM flights
    UNION ALL
    SELECT 'DEPARTURE_DELAY', COUNT(*) - COUNT(DEPARTURE_DELAY) FROM flights
    UNION ALL
    SELECT 'TAXI_OUT', COUNT(*) - COUNT(TAXI_OUT) FROM flights
    UNION ALL
    SELECT 'WHEELS_OFF', COUNT(*) - COUNT(WHEELS_OFF) FROM flights
    UNION ALL
    SELECT 'SCHEDULED_TIME', COUNT(*) - COUNT(SCHEDULED_TIME) FROM flights
    UNION ALL
    SELECT 'ELAPSED_TIME', COUNT(*) - COUNT(ELAPSED_TIME) FROM flights
    UNION ALL
    SELECT 'AIR_TIME', COUNT(*) - COUNT(AIR_TIME) FROM flights
    UNION ALL
    SELECT 'WHEELS_ON', COUNT(*) - COUNT(WHEELS_ON) FROM flights
    UNION ALL
    SELECT 'TAXI_IN', COUNT(*) - COUNT(TAXI_IN) FROM flights
    UNION ALL
    SELECT 'ARRIVAL_TIME', COUNT(*) - COUNT(ARRIVAL_TIME) FROM flights
    UNION ALL
    SELECT 'ARRIVAL_DELAY', COUNT(*) - COUNT(ARRIVAL_DELAY) FROM flights
    UNION ALL
    SELECT 'CANCELLATION_REASON', COUNT(*) - COUNT(CANCELLATION_REASON) FROM flights
    UNION ALL
    SELECT 'AIR_SYSTEM_DELAY', COUNT(*) - COUNT(AIR_SYSTEM_DELAY) FROM flights
    UNION ALL
    SELECT 'SECURITY_DELAY', COUNT(*) - COUNT(SECURITY_DELAY) FROM flights
    UNION ALL
    SELECT 'AIRLINE_DELAY', COUNT(*) - COUNT(AIRLINE_DELAY) FROM flights
    UNION ALL
    SELECT 'LATE_AIRCRAFT_DELAY', COUNT(*) - COUNT(LATE_AIRCRAFT_DELAY) FROM flights
    UNION ALL
    SELECT 'WEATHER_DELAY', COUNT(*) - COUNT(WEATHER_DELAY) FROM flights
) AS null_check
WHERE null_count > 0
ORDER BY null_count DESC;

--- Checking For null values in airports column ---
SELECT * FROM airports
SELECT column_name, null_count
FROM (
        SELECT 'IATA_CODE' AS column_name, COUNT(*) - COUNT(IATA_CODE) AS null_count FROM airports
        UNION ALL
        SELECT 'AIRPORT' AS column_name, COUNT(*) - COUNT(AIRPORT) AS null_count FROM airports
        UNION ALL
        SELECT 'CITY' AS column_name, COUNT(*) - COUNT(CITY) AS null_count FROM airports
        UNION ALL
        SELECT 'STATE' AS column_name, COUNT(*) - COUNT(STATE) AS null_count FROM airports
        UNION ALL
        SELECT 'COUNTRY' AS column_name, COUNT(*) - COUNT(COUNTRY) AS null_count FROM airports
        UNION ALL
        SELECT 'LATITUDE' AS column_name, COUNT(*) - COUNT(LATITUDE) AS null_count FROM airports
        UNION ALL
        SELECT 'LONGITUDE' AS column_name, COUNT(*) - COUNT(LONGITUDE) AS null_count FROM airports
       )AS null_check
WHERE null_count >0
ORDER BY null_count DESC;

--- CHECKING airlines dataset and no null vlaues found ---
SELECT * FROM airlines



